---
- name: jenkins
  box: centos/7
  cpus: 1
  memory: 2048
  forwarded_ports:
  - guest: 9000
    host: 9000
  - guest: 9000
    host: 9001
  package_manager: yum
  packages:
  - git
  - vim
    #shared_folders:
    #- host: ~/shared_vagrant
    # guest: /home/vagrant/shared
  scripts:
  - install_server
  - install_jenkins
- name: server
  box: centos/7
  cpus: 1
  memory: 2048
  forwarded_ports:
  - guest: 9000
    host: 9010
  - guest: 9000
    host: 9011
  package_manager: yum
  packages:
  - git
  - vim
  shared_folders:
  - host: ~/shared_vagrant
    guest: /home/vagrant/shared
  scripts:
  - install_server
...
